version: "3.7"
services:
  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:8.1.0
    environment:
      S_JAVA_OPTS: '-Xms256m -Xmx256m'
      cluster.name: es-cluster
      node.name: es1
      discovery.type: single-node
      network.bind_host: 0.0.0.0
      xpack.security.enabled: 'false'
      http.cors.enabled : 'true'
      http.cors.allow-origin : "*"
      http.cors.allow-methods : OPTIONS, HEAD, GET, POST, PUT, DELETE
      http.cors.allow-headers : X-Requested-With,X-Auth-Token,Content-Type, Content-Length
      logger.level: debug
      http.max_content_length: 1000MB
    networks:
      - elastic
    ports:
      - 9200:9200
    volumes:
      - $PWD/es_data:/usr/share/elasticsearch/data
  kibana:
    container_name: kb-container
    image: docker.elastic.co/kibana/kibana:8.1.0
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    networks:
      - elastic
    depends_on:
      - elasticsearch
    ports:
      - 5601:5601
  dejavu:
    container_name: dejavu
    image: appbaseio/dejavu
    ports:
      - 1358:1358
networks:
  elastic:
    driver: bridge